# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/truco',
                'doc_host': 'https://lgvaz.github.io',
                'git_url': 'https://github.com/lgvaz/truco',
                'lib_path': 'truco'},
  'syms': { 'truco.core': { 'truco.core.cards2ranks': ('core.html#cards2ranks', 'truco/core.py'),
                            'truco.core.get_trump_round_rank': ('core.html#get_trump_round_rank', 'truco/core.py')},
            'truco.core_old': {'truco.core_old.foo': ('core_old.html#foo', 'truco/core_old.py')},
            'truco.monte': {'truco.monte.foo': ('core_old-copy1.html#foo', 'truco/monte.py')}}}
